import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const production = process.argv.includes("--production");

const banner = "/* THIS IS A GENERATED BUNDLE FILE\n * Source: https://github.com/emmet24/obsidian-opencode-wsl\n */\n";

async function main() {
  // Step 1: Build bridge.js
  const bridgeCtx = await esbuild.context({
    entryPoints: ["src/bridge/server.ts"],
    bundle: true,
    external: ["node-pty"],
    format: "cjs",
    platform: "node",
    target: "node18",
    sourcemap: false,
    treeShaking: true,
    outfile: "bridge.js",
    minify: production,
  });
  await bridgeCtx.rebuild();
  await bridgeCtx.dispose();

  // Step 2: Inline bridge.js into main.js as base64
  const bridgeJs = readFileSync(join(__dirname, "bridge.js"), "utf-8");
  const base64 = Buffer.from(bridgeJs, "utf-8").toString("base64");
  writeFileSync(
    join(__dirname, "src", "bridgeEmbed.ts"),
    `// This file is auto-generated by esbuild.config.mjs\nexport const BRIDGE_JS_BASE64 = ${JSON.stringify(base64)};\n`
  );

  // Step 3: Build main.js (plugin)
  const context = await esbuild.context({
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtinModules,
    ],
    banner: { js: banner },
    format: "cjs",
    target: "es2018",
    sourcemap: production ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: production,
  });

  if (production) {
    await context.rebuild();
    await context.dispose();
  } else {
    await context.watch();
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});