#!/usr/bin/env node
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const bridgeJs = readFileSync(join(root, "bridge.js"), "utf-8");
const base64 = Buffer.from(bridgeJs, "utf-8").toString("base64");

writeFileSync(
  join(root, "src", "bridgeEmbed.ts"),
  `// This file is auto-generated by scripts/inline-bridge.mjs
export const BRIDGE_JS_BASE64 = ${JSON.stringify(base64)};
`
);
console.log("Generated src/bridgeEmbed.ts");